---
    name: Auto Tag and Release
    on:
      pull_request:
        types:
          - closed
        branches:
          - main
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v4.1.0
            with:
              ref: ${{ github.event.pull_request.head.sha }}
              fetch-depth: "0"
    
          - id: auto-tag
            name: "Bump/tag version"
            uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36 #v1.6.7
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              WITH_V: true
              RELEASE_BRANCHES: main
              DEFAULT_BUMP: patch
              INITIAL_VERSION: "0.0.1"
    
          - name: Create GitHub release
            uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 #v1.13.0
            with:
              tag: ${{ steps.auto-tag.outputs.new_tag }}
              token: ${{ secrets.GITHUB_TOKEN }}
              generateReleaseNotes: true